version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "my_db"
    env_file:
      - ./../.env
    ports:
      - "54320:5432"
    volumes:
      - ./../database:/var/lib/postgresql/data