FROM python:3.7-slim   

ENV DOCKER=T

COPY ./app /root/app
COPY ./requirements.txt /root/requirements.txt
COPY ./run.py /root

WORKDIR /root

RUN pip install -r requirements.txt

EXPOSE 5000

CMD ["python", "run.py"]